<?php
return [
    'AuthController@register' => [
        'name' => 'Imran Hossain',
        'email' => 'imran@example.com',
        'password' => 'secret123',
        'role' => 'admin',
        'phone' => '+8801712345678',
        'grade_id' => 1,
    ],
    'AuthController@login' => [
        'email' => 'imran@example.com',
        'password' => 'secret123',
    ],
    'AuthController@requestOtp' => [
        'email' => 'imran@example.com',
        'type' => 'email',
    ],
    'AuthController@verifyOtp' => [
        'email' => 'imran@example.com',
        'otp' => '123456',
        'two_factor_type' => 'email',
    ],
    'AuthController@forgotPassword' => [
        'email' => 'imran@example.com',
    ],
    'AuthController@resetPassword' => [
        'email' => 'imran@example.com',
        'otp' => '123456',
        'password' => 'newStrongPassword!1',
    ],
    'UserController@store' => [
        'name' => 'Afsana Karim',
        'email' => 'afsana@example.com',
        'password' => 'tempPass!23',
        'role' => 'manager',
        'phone' => '+8801812345678',
        'grade_id' => 2,
    ],
    'UserController@update' => [
        'name' => 'Afsana Rahman',
        'phone' => '+8801812348888',
        'role' => 'manager',
    ],
    'CustomerController@store' => [
        'name' => 'Md. Farhan Islam',
        'NID' => '1999123412345',
        'phone' => '01712345678',
        'address' => 'House 12, Road 3, Dhanmondi, Dhaka',
        'email' => 'farhan@example.com',
        'status' => 'new',
        'membership_type' => 'general',
        'is_investor' => 1,
        'bank_info' => 'BRAC Bank, A/C 123456789',
        'nominee' => 'Sharmin Akter',
    ],
    'CustomerController@update' => [
        'name' => 'Farhan Islam',
        'NID' => '1999123412345',
        'phone' => '01798765432',
        'address' => 'Apartment 5B, Mirpur DOHS, Dhaka',
        'email' => 'investor.farhan@example.com',
        'status' => 'verified',
        'is_investor' => 1,
        'investor_no' => 'INV-2045',
    ],
    'CustomerController@verifyDocuments' => [
        'nid_verified' => true,
        'police_verified' => true,
    ],
    'BookingController@store' => [
        'customer_id' => 42,
        'room_type' => 'Deluxe Suite',
        'guest_count' => 2,
        'check_in' => '2024-08-01',
        'check_out' => '2024-08-05',
        'price_plan' => 'Corporate',
        'payment_method' => 'card',
        'amount' => 48000,
        'payment_status' => 'pending',
    ],
    'BookingController@update' => [
        'customer_id' => 42,
        'room_type' => 'Executive Suite',
        'guest_count' => 3,
        'check_in' => '2024-08-02',
        'check_out' => '2024-08-06',
        'price_plan' => 'Corporate',
        'payment_method' => 'card',
        'amount' => 52000,
        'payment_status' => 'paid',
    ],
    'BookingController@cancel' => [
        'refund_amount' => 12000,
    ],
    'SharePackageController@store' => [
        'project_id' => 7,
        'package_name' => 'Gold Growth Plan',
        'package_code' => 'GOLD-500',
        'package_price' => 500000,
        'down_payment' => 150000,
        'total_shares_included' => 50,
        'bonus_shares' => 5,
        'installment_months' => 12,
        'status' => 'active',
        'benefits' => [
            'priority_allocation' => true,
            'vip_support' => true,
        ],
        'benefit_items' => [
            ['label' => 'Free annual audit', 'value' => 'Included'],
            ['label' => 'Dividend booster', 'value' => '1.5x'],
        ],
    ],
    'SharePackageController@update' => [
        'project_id' => 7,
        'package_name' => 'Gold Growth Plan+',
        'package_code' => 'GOLD-500',
        'package_price' => 520000,
        'down_payment' => 180000,
        'total_shares_included' => 55,
        'bonus_shares' => 7,
        'installment_months' => 10,
        'status' => 'active',
        'benefits' => [
            'priority_allocation' => true,
            'vip_support' => true,
            'dedicated_rm' => true,
        ],
        'benefit_items' => [
            ['label' => 'Priority payout', 'value' => 'Quarterly'],
        ],
    ],
    'SharePackageController@updateStatus' => [
        'status' => 'inactive',
    ],
    'ProjectController@store' => [
        'project_code' => 'PRJ-OCN-01',
        'project_name' => 'Oceanview Residency',
        'location' => 'Cox\'s Bazar',
        'description' => 'Premium seaside condominium project.',
        'status' => 'active',
        'certificate_prefix' => 'OCN',
    ],
    'ProjectController@update' => [
        'project_code' => 'PRJ-OCN-01',
        'project_name' => 'Oceanview Residency Phase 2',
        'location' => 'Cox\'s Bazar',
        'description' => 'Expanded tower with rooftop amenities.',
        'status' => 'active',
        'certificate_prefix' => 'OCN',
    ],
    'ShareBatchController@store' => [
        'project_id' => 7,
        'batch_name' => 'Batch A-2024',
        'share_price' => 25000,
        'total_shares' => 500,
        'available_shares' => 500,
        'certificate_start_no' => 1001,
        'certificate_end_no' => 1500,
        'status' => 'active',
    ],
    'ShareBatchController@update' => [
        'project_id' => 7,
        'batch_name' => 'Batch A-2024 Rev-1',
        'share_price' => 26000,
        'total_shares' => 520,
        'available_shares' => 400,
        'certificate_start_no' => 1001,
        'certificate_end_no' => 1520,
        'status' => 'inactive',
    ],
    'ShareSalesController@sellSingle' => [
        'customer_id' => 12,
        'project_id' => 3,
        'share_units' => 10,
        'share_price' => 25000,
        'payment_mode' => 'installment',
        'down_payment' => 75000,
        'installment_months' => 12,
        'stage' => 'MÖW-101',
    ],
    'ShareSalesController@sellPackage' => [
        'customer_id' => 12,
        'project_id' => 3,
        'package_id' => 5,
        'payment_mode' => 'one_time',
        'down_payment' => 500000,
        'installment_months' => 1,
        'stage' => 'MÖW-101',
    ],
    'ShareSalesController@sellSingleSelf' => [
        'project_id' => 3,
        'share_units' => 5,
        'share_price' => 25000,
        'payment_mode' => 'installment',
        'down_payment' => 50000,
        'installment_months' => 6,
        'stage' => 'MÖW-201',
    ],
    'ShareSalesController@sellPackageSelf' => [
        'project_id' => 3,
        'package_id' => 5,
        'payment_mode' => 'installment',
        'down_payment' => 200000,
        'installment_months' => 8,
        'stage' => 'MÖW-201',
    ],
    'TransactionController@store' => [
        'share_id' => 88,
        'amount' => 125000,
        'payment_type' => 'bank_transfer',
        'date' => '2024-07-15',
        'note' => 'Initial investment payment',
    ],
    'TransactionController@update' => [
        'amount' => 130000,
        'payment_type' => 'cash',
        'date' => '2024-07-18',
        'note' => 'Adjusted after reconciliation',
    ],
    'GradeController@store' => [
        'grade_no' => 3,
        'grade_name' => 'Senior Executive',
        'description' => 'Leadership level for experienced managers.',
        'status' => 'active',
    ],
    'GradeController@update' => [
        'grade_no' => 3,
        'grade_name' => 'Senior Executive II',
        'description' => 'Eligible for stock grants.',
        'status' => 'active',
    ],
    'DesignationController@store' => [
        'grade_id' => 3,
        'designation_name' => 'Regional Sales Lead',
        'description' => 'Leads divisional sales teams.',
        'status' => 'active',
    ],
    'DesignationController@update' => [
        'grade_id' => 3,
        'designation_name' => 'Regional Sales Director',
        'description' => 'Oversees all regional operations.',
        'status' => 'active',
    ],
    'EmployeeController@store' => [
        'name' => 'Sonia Akter',
        'father_name' => 'Rezaul Karim',
        'mother_name' => 'Hosne Ara',
        'nid' => '1988123412345',
        'address' => 'Nikunja 2, Dhaka',
        'phone' => '01755667788',
        'email' => 'sonia.akter@example.com',
        'education' => 'MBA in Finance',
        'grade_id' => 3,
        'designation_id' => 4,
        'join_date' => '2022-04-01',
        'salary' => 85000,
        'documents' => ['nid_copy', 'photo', 'appointment_letter'],
        'status' => 'active',
    ],
    'EmployeeController@update' => [
        'name' => 'Sonia Akter Khan',
        'father_name' => 'Rezaul Karim',
        'mother_name' => 'Hosne Ara',
        'nid' => '1988123412345',
        'address' => 'Gulshan 1, Dhaka',
        'phone' => '01755660000',
        'email' => 'sonia.khan@example.com',
        'education' => 'MBA in Finance',
        'grade_id' => 3,
        'designation_id' => 5,
        'join_date' => '2022-04-01',
        'salary' => 95000,
        'documents' => ['nid_copy', 'photo', 'promotion_letter'],
        'status' => 'probation',
    ],
    'EmployeeController@checkIn' => [
        'check_in_at' => '2024-07-18 09:15:00',
        'source' => 'mobile_app',
        'status' => 'present',
    ],
    'EmployeeController@checkOut' => [
        'check_out_at' => '2024-07-18 18:05:00',
    ],
    'EmployeeController@leaveStore' => [
        'type' => 'sick',
        'from_date' => '2024-07-20',
        'to_date' => '2024-07-22',
        'reason' => 'Seasonal flu',
    ],
    'EmployeeController@leaveUpdate' => [
        'type' => 'sick',
        'from_date' => '2024-07-20',
        'to_date' => '2024-07-23',
        'status' => 'pending',
        'reason' => 'Doctor advised extra rest',
    ],
    'EmployeeController@leaveApprove' => [
        'status' => 'approved',
    ],
    'EmployeeController@kpiStore' => [
        'period_start' => '2024-07-01',
        'period_end' => '2024-07-31',
        'target' => 30,
        'achieved' => 27,
        'score' => 90,
        'remarks' => 'Strong close rate',
    ],
    'EmployeeController@verifyDocuments' => [
        'nid_verified' => true,
        'police_verified' => false,
    ],
    'LeadController@store' => [
        'officer_id' => 9,
        'name' => 'Tanvir Hasan',
        'contact' => '+8801912345678',
        'email' => 'tanvir.lead@example.com',
        'source' => 'Expo booth',
        'status' => 'lead',
    ],
    'LeadController@update' => [
        'officer_id' => 9,
        'name' => 'Tanvir Hasan',
        'contact' => '+8801999988888',
        'status' => 'prospect',
        'notes' => 'Interested in premium package',
    ],
    'LeadController@convertToProspect' => [
        'notes' => 'Attended onsite visit',
    ],
    'LeadController@convertToInvestor' => [
        'customer_id' => 12,
        'notes' => 'Invested in Oceanview project',
    ],
    'LeadController@storeReminder' => [
        'remind_at' => '2024-07-25 10:00:00',
        'note' => 'Follow-up call on share allocation',
        'status' => 'pending',
    ],
    'ApprovalController@store' => [
        'module' => 'share_sales',
        'record_id' => 51,
        'approver_id' => 3,
        'status' => 'pending',
        'remarks' => 'Awaiting finance review',
    ],
    'ApprovalController@update' => [
        'status' => 'approved',
        'approved_at' => '2024-07-18 14:45:00',
        'remarks' => 'All documents verified',
    ],
    'AccountController@store' => [
        'code' => '1010',
        'name' => 'Cash in Hand',
        'category' => 'asset',
        'type' => 'current_asset',
        'parent_id' => null,
        'is_active' => 1,
        'description' => 'Cash kept at head office',
    ],
    'AccountController@update' => [
        'name' => 'Cash & Equivalents',
        'is_active' => 1,
        'description' => 'Petty cash and equivalents',
    ],
    'VoucherController@store' => [
        'voucher_no' => 'RV-2024-0718',
        'voucher_type' => 'receipt',
        'date' => '2024-07-18',
        'description' => 'Installment collection',
        'status' => 'draft',
        'lines' => [
            ['account_id' => 1, 'debit' => 150000, 'credit' => 0, 'description' => 'Cash received'],
            ['account_id' => 55, 'debit' => 0, 'credit' => 150000, 'description' => 'Installment income'],
        ],
    ],
    'InstallmentController@store' => [
        'related_type' => 'customer_share',
        'related_id' => 10,
        'due_date' => '2024-09-01',
        'amount' => 25000,
        'status' => 'pending',
    ],
    'InstallmentController@pay' => [
        'installment_id' => 44,
        'payment' => [
            'amount' => 25000,
            'channel' => 'bank_transfer',
            'reference_no' => 'TRX-2024-0001',
            'bank_name' => 'BRAC Bank',
            'transaction_id' => 'NEFT9988',
            'note' => 'July installment collection',
            'received_at' => '2024-07-18 10:30:00',
        ],
    ],
    'InstallmentController@markPaid' => [
        'payment' => [
            'channel' => 'cash',
            'note' => 'Paid at counter',
            'received_at' => '2024-07-18 09:15:00',
        ],
    ],
    'InstallmentController@payShareSaleInstallment' => [
        'payment' => [
            'amount' => 30000,
            'channel' => 'sslcommerz',
            'gateway' => 'sslcommerz',
            'transaction_id' => 'SSL-449922',
            'reference_no' => 'RCPT-2024-300',
            'note' => 'Installment for Oceanview sale',
            'received_at' => '2024-07-19 12:05:00',
        ],
    ],
    'PayrollController@store' => [
        'period_start' => '2024-07-01',
        'period_end' => '2024-07-31',
    ],
    'StageController@closePeriod' => [
        'customer_id' => 15,
        'profit_amount' => 42000,
        'period_start' => '2024-06-01',
        'period_end' => '2024-06-30',
    ],
    'StageController@upgrade' => [
        'stage_id' => 4,
    ],
    'PolicyController@store' => [
        'code' => 'HR-POL-001',
        'title' => 'Remote Work Policy',
        'description' => 'Guidelines for hybrid and remote work.',
        'version' => '1.0',
        'effective_from' => '2024-07-01',
        'status' => 'active',
    ],
    'PolicyController@update' => [
        'code' => 'HR-POL-001',
        'title' => 'Remote Work Policy',
        'description' => 'Updated policy with security clause.',
        'version' => '1.1',
        'effective_from' => '2024-07-01',
        'effective_to' => '2025-06-30',
        'status' => 'active',
        'change_summary' => 'Added VPN requirements',
        'approved_by' => ['COO', 'CTO'],
    ],
    'SettingController@update' => [
        'value' => 'noreply@hurream.com',
        'type' => 'string',
        'description' => 'Default sender for transactional emails',
    ],
    'NotificationTemplateController@store' => [
        'code' => 'WELCOME_MAIL',
        'channel' => 'email',
        'subject' => 'Welcome to Hurream ERP',
        'body' => 'Hello {{name}}, your account is live.',
        'placeholders' => ['name', 'login_url'],
        'status' => 'active',
    ],
    'NotificationTemplateController@update' => [
        'code' => 'WELCOME_MAIL',
        'channel' => 'email',
        'subject' => 'Welcome to Hurream ERP',
        'body' => 'Hi {{name}}, you can login at {{login_url}}',
        'placeholders' => ['name', 'login_url'],
        'status' => 'inactive',
    ],
    'NotificationTemplateController@render' => [
        'data' => [
            'name' => 'Imran',
            'login_url' => 'https://erp.hurream.com/login',
        ],
    ],
];
